import 'package:market_list_with_flutter/domain/entities/product.dart';

var mockedItems = <Product>[
  Product(id: 1, name: 'Papel Toalha', quantity: 1),
  Product(id: 2, name: 'Arroz', quantity: 1),
  Product(id: 3, name: 'Feijão', quantity: 1),
  Product(id: 4, name: 'Açúcar', quantity: 1),
  Product(id: 5, name: 'Óleo', quantity: 1),
  Product(id: 6, name: 'Sabonete', quantity: 1),
  Product(id: 7, name: 'Creme Dental', quantity: 1),
  Product(id: 8, name: 'Vinagre', quantity: 1),
  Product(id: 9, name: 'Água Sanitária', quantity: 1),
  Product(id: 10, name: 'Manteiga', quantity: 1),
  Product(id: 11, name: 'Café', quantity: 1),
  Product(id: 12, name: 'Filtro de Café', quantity: 1),
  Product(id: 13, name: 'Biscoito', quantity: 1),
  Product(id: 14, name: 'Leite', quantity: 1),
  Product(id: 15, name: 'Macarrão', quantity: 1),
  Product(id: 16, name: 'Farofa', quantity: 1),
  Product(id: 17, name: 'Azeite', quantity: 1),
  Product(id: 18, name: 'Bom Bril', quantity: 1),
  Product(id: 19, name: 'Fósforo', quantity: 1),
  Product(id: 20, name: 'Bucha', quantity: 1),
  Product(id: 21, name: 'Papel Higiênico', quantity: 1),
  Product(id: 22, name: 'Amanciante de Roupa', quantity: 1),
  Product(id: 23, name: 'Detergente', quantity: 1),
  Product(id: 24, name: 'Sabão em Pó', quantity: 1),
  Product(id: 25, name: 'Desodorante', quantity: 1),
  Product(id: 26, name: 'Listerine', quantity: 1),
  Product(id: 27, name: 'Cotonete', quantity: 1),
  Product(id: 28, name: 'Sabão de Coco', quantity: 1),
  Product(id: 29, name: 'Sabão em Pedra', quantity: 1),
  Product(id: 30, name: 'Bolacha', quantity: 1),
  Product(id: 31, name: 'Tang', quantity: 1),
];
